version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-livewire-filter-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-livewire-filter-network

  nginx:
    image: nginx:alpine
    container_name: laravel-livewire-filter-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-livewire-filter-network

  mysql:
    image: mysql:8.0
    container_name: laravel-livewire-filter-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_livewire_filter
      MYSQL_USER: laravel-livewire-filter
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-livewire-filter-network

networks:
  laravel-livewire-filter-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
